name: Test Action
on: [push]

jobs:
  get-num-square:
    runs-on: ubuntu-latest
    name: return the number square
    step:
      -name: Checkout
       uses: action/setup-python@v4
      -name: fetch num squared
       id: get_square
       uses: ./
       with:
        num: 11
      -num: print the square
       run: echo "${{steps.get_square.outputs.num_squared }}"
